<a href="https://colab.research.google.com/github/chitsikaR/CHTTEN011_FinalYearProject/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/dos_dataset/clean_2.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 75 columns):
 #   Column                        Non-Null Count    Dtype  
---  ------                        --------------    -----  
 0   Unnamed: 0                    1245798 non-null  int64  
 1   Unnamed: 0.1                  1245798 non-null  int64  
 2   Unnamed: 0.1.1                1245798 non-null  int64  
 3    Source IP                    1245798 non-null  int64  
 4    Source Port                  1245798 non-null  int64  
 5    Destination IP               1245798 non-null  int64  
 6    Destination Port             1245798 non-null  int64  
 7    Protocol                     1245798 non-null  int64  
 8    Flow Duration                1245798 non-null  int64  
 9    Total Fwd Packets            1245798 non-null  int64  
 10   Total Backward Packets       1245798 non-null  int64  
 11  Total Length of Fwd Packets   1245798 non-null  float64
 12   Total Length of Bwd Packets

In [ ]:
df=df.drop(' Source IP',axis=1)
df=df.drop(' Flow Duration',axis=1)
#df=df.drop(' Total Fwd Packets',axis=1)
#df=df.drop(' Total Backward Packets',axis=1)
df=df.drop(' Total Length of Bwd Packets',axis=1)
df=df.drop(' Fwd Packet Length Std',axis=1)
df=df.drop(' Flow IAT Max',axis=1)
df=df.drop(' Flow IAT Min',axis=1)
#df=df.drop('Fwd IAT Total',axis=1)
df=df.drop(' Fwd IAT Max',axis=1)
df=df.drop(' Fwd IAT Min',axis=1)
df=df.drop('Bwd IAT Total',axis=1)
df=df.drop(' Bwd IAT Mean',axis=1)
df=df.drop(' Bwd IAT Std',axis=1)
df=df.drop(' Bwd IAT Max',axis=1)
df=df.drop(' Bwd IAT Min',axis=1)
#df=df.drop(' Fwd Header Length',axis=1)
df=df.drop(' Bwd Header Length',axis=1)
df=df.drop(' Bwd Packets/s',axis=1)
df=df.drop(' SYN Flag Count',axis=1)
df=df.drop(' Down/Up Ratio',axis=1)
df=df.drop(' Fwd Header Length.1',axis=1)
df=df.drop('Subflow Fwd Packets',axis=1)
df=df.drop(' Subflow Bwd Packets',axis=1)
df=df.drop(' Subflow Bwd Bytes',axis=1)
df=df.drop(' act_data_pkt_fwd',axis=1)
df=df.drop(' min_seg_size_forward',axis=1)
df=df.drop('Active Mean',axis=1)
df=df.drop(' Active Std',axis=1)
df=df.drop(' Active Max',axis=1)
df=df.drop(' Active Min',axis=1)
df=df.drop('Idle Mean',axis=1)
df=df.drop(' Idle Max',axis=1)
df=df.drop(' Idle Min',axis=1)
df = df.drop(' Packet Length Std',axis=1)


In [ ]:
df = df.drop('Flow Bytes/s',axis=1)
df = df.drop(' Flow Packets/s',axis=1)

In [ ]:
df=df.drop('Unnamed: 0',axis=1)
df=df.drop('Unnamed: 0.1',axis=1)
df=df.drop('Unnamed: 0.1.1',axis=1)
df=df.drop(' Source Port',axis=1)
df=df.drop(' Destination IP',axis=1)
df=df.drop(' Destination Port',axis=1)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 36 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0    Protocol                    1245798 non-null  int64  
 1    Total Fwd Packets           1245798 non-null  int64  
 2    Total Backward Packets      1245798 non-null  int64  
 3   Total Length of Fwd Packets  1245798 non-null  float64
 4    Fwd Packet Length Max       1245798 non-null  float64
 5    Fwd Packet Length Min       1245798 non-null  float64
 6    Fwd Packet Length Mean      1245798 non-null  float64
 7   Bwd Packet Length Max        1245798 non-null  float64
 8    Bwd Packet Length Min       1245798 non-null  float64
 9    Bwd Packet Length Mean      1245798 non-null  float64
 10   Bwd Packet Length Std       1245798 non-null  float64
 11   Flow IAT Mean               1245798 non-null  float64
 12   Flow IAT Std                1245798 non-n

In [ ]:
#df=df.drop('Unnamed: 0.1',axis=1)
x=df.iloc[:,df.columns != 'Label']
y=df.iloc[:,-1]
print("x\n",x.info())
y = pd.DataFrame(y)
print('y\n',y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 35 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0    Protocol                    1245798 non-null  int64  
 1    Total Fwd Packets           1245798 non-null  int64  
 2    Total Backward Packets      1245798 non-null  int64  
 3   Total Length of Fwd Packets  1245798 non-null  float64
 4    Fwd Packet Length Max       1245798 non-null  float64
 5    Fwd Packet Length Min       1245798 non-null  float64
 6    Fwd Packet Length Mean      1245798 non-null  float64
 7   Bwd Packet Length Max        1245798 non-null  float64
 8    Bwd Packet Length Min       1245798 non-null  float64
 9    Bwd Packet Length Mean      1245798 non-null  float64
 10   Bwd Packet Length Std       1245798 non-null  float64
 11   Flow IAT Mean               1245798 non-null  float64
 12   Flow IAT Std                1245798 non-n

In [ ]:
#normalized_df=(df-df.mean())/df.std()
#normalized_x=normalized_df.iloc[:,normalized_df.columns != 'Label']
#y=pd.DataFrame(y)

In [ ]:
df.head()

Protocol   Total Fwd Packets  ...   Inbound  Label
0          6                   4  ...         1      2
1          6                   2  ...         1      2
2          6                   4  ...         1      2
3          6                   4  ...         1      2
4         17                   2  ...         1      2

[5 rows x 36 columns]

In [ ]:
normalized_df=(df-df.mean())/df.std()

In [ ]:
y=pd.DataFrame(y)

In [ ]:
normalized_x=normalized_df.iloc[:,normalized_df.columns != 'Label']

In [ ]:
normalized_df.describe()

Protocol   Total Fwd Packets  ...       Inbound         Label
count  1.245798e+06        1.245798e+06  ...  1.245798e+06  1.245798e+06
mean  -1.240177e-11        5.754005e-15  ... -2.792804e-12 -4.782956e-12
std    1.000000e+00        1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -3.406373e+00       -1.236954e-02  ... -5.061243e+00 -1.822172e+00
25%    4.899846e-01       -7.162054e-03  ...  1.975798e-01 -7.310472e-01
50%    4.899846e-01       -7.162054e-03  ...  1.975798e-01 -1.854849e-01
75%    4.899846e-01       -7.162054e-03  ...  1.975798e-01  9.056397e-01
max    4.899846e-01        4.523355e+02  ...  1.975798e-01  1.996764e+00

[8 rows x 36 columns]

In [ ]:
normalized_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 35 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0    Protocol                    1245798 non-null  float64
 1    Total Fwd Packets           1245798 non-null  float64
 2    Total Backward Packets      1245798 non-null  float64
 3   Total Length of Fwd Packets  1245798 non-null  float64
 4    Fwd Packet Length Max       1245798 non-null  float64
 5    Fwd Packet Length Min       1245798 non-null  float64
 6    Fwd Packet Length Mean      1245798 non-null  float64
 7   Bwd Packet Length Max        1245798 non-null  float64
 8    Bwd Packet Length Min       1245798 non-null  float64
 9    Bwd Packet Length Mean      1245798 non-null  float64
 10   Bwd Packet Length Std       1245798 non-null  float64
 11   Flow IAT Mean               1245798 non-null  float64
 12   Flow IAT Std                1245798 non-n

In [ ]:
y.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 1 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Label   1245798 non-null  int64
dtypes: int64(1)
memory usage: 9.5 MB


KNN Classifier

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
models = [LogisticRegression(), KNeighborsClassifier(n_neighbors=3),MLPClassifier(alpha=0.005),DecisionTreeClassifier()]
classifiers = ["LR", "KNN","MLP","DecisionTree"]
scores = []

In [ ]:
#checks whether there are NaN values in the normalizex_x dataframe
#np.any(np.isnan(normalized_x))

In [ ]:
#fills NaN values with the mean value
#normalized_x = normalized_x.fillna(X.mean())


In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(normalized_x, y, test_size=0.25, random_state=42)
y_train = np.array(y_train)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [ ]:
from sklearn import metrics
y_pred = model.predict(X_test)
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))

Accuracy = 0.8622828704446942


In [ ]:
#from sklearn import metrics
from sklearn.metrics import f1_score

print('K Nearest Neighbour Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

K Nearest Neighbour Classifier
Accuracy =  86.22828704446943
Confusion Matrix =
 [[14227     1     0     0     7     0     1     0]
 [    3 20311     3    14 29573     0    13     0]
 [    4     3 49776    70    17     0     1     0]
 [    3     6   793 49032    35     0   417     6]
 [   14 10833     0    28 35701     0    13    10]
 [    2     0     0     2     1 50173     1     2]
 [    0     3     0   863     7     0 49001    25]
 [    4     0     0     6    23     0    85   337]]
Recall = 0.8622828704446942
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14236
           1       0.65      0.41      0.50     49917
           2       0.98      1.00      0.99     49871
           3       0.98      0.97      0.98     50292
           4       0.55      0.77      0.64     46599
           5       1.00      1.00      1.00     50181
           6       0.99      0.98      0.99     49899
           7       0.89 

In [ ]:
for model in models:
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)*100
    scores.append(score)
    print("Accuracy of the model is: ", score)
    conf_matrix = confusion_matrix(y_test,y_pred)
    report = classification_report(y_test,y_pred)
    print("Confusion Matrix:\n",conf_matrix)
    print("Report:\n",report)
    print("\n==============***===============")

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

In [ ]:
pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Naive Bayes')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))